CRITICAL - 2025-06-21 11:43:44 --> Error: Class "App\Models\ConsultaModel" not found
[Method: GET, Route: admin/consultas]
in APPPATH\Controllers\back\Consultas.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Consultas->index()
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Consultas))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 11:44:27 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/plantilla_admin.php
[Method: GET, Route: admin]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/plantilla_admin.php')
 2 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('layouts/plantilla_admin', [], true)
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/panel', [], true)
 4 APPPATH\Controllers\back\Admin.php(13): view('back/panel')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Admin->panel()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Admin))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 11:46:34 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/sidebar_admin.php
[Method: GET, Route: admin]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/sidebar_admin.php')
 2 SYSTEMPATH\View\View.php(475): CodeIgniter\View\View->render('layouts/sidebar_admin', null, true)
 3 APPPATH\Views\back\layouts\plantilla_admin.php(22): CodeIgniter\View\View->include('layouts/sidebar_admin')
 4 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\layouts\\plantilla_admin.php')
 5 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('back/layouts/plantilla_admin', [], true)
 7 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/panel', [], true)
 8 APPPATH\Controllers\back\Admin.php(13): view('back/panel')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Admin->panel()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Admin))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 11:46:41 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/header.php
[Method: GET, Route: /]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/header.php')
 2 SYSTEMPATH\View\View.php(475): CodeIgniter\View\View->render('layouts/header', null, true)
 3 APPPATH\Views\front\layouts\plantilla.php(25): CodeIgniter\View\View->include('layouts/header')
 4 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\layouts\\plantilla.php')
 5 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('front/layouts/plantilla', [], true)
 7 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/principal', [], true)
 8 APPPATH\Controllers\front\Principal.php(12): view('front/principal')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Principal->index()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Principal))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 11:47:22 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/header.php
[Method: GET, Route: /]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/header.php')
 2 SYSTEMPATH\View\View.php(475): CodeIgniter\View\View->render('layouts/header', null, true)
 3 APPPATH\Views\front\layouts\plantilla.php(25): CodeIgniter\View\View->include('layouts/header')
 4 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\layouts\\plantilla.php')
 5 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('front/layouts/plantilla', [], true)
 7 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/principal', [], true)
 8 APPPATH\Controllers\front\Principal.php(12): view('front/principal')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Principal->index()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Principal))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 11:48:04 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/sidebar_admin.php
[Method: GET, Route: admin]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/sidebar_admin.php')
 2 SYSTEMPATH\View\View.php(475): CodeIgniter\View\View->render('layouts/sidebar_admin', null, true)
 3 APPPATH\Views\back\layouts\plantilla_admin.php(22): CodeIgniter\View\View->include('layouts/sidebar_admin')
 4 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\layouts\\plantilla_admin.php')
 5 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('back/layouts/plantilla_admin', [], true)
 7 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/panel', [], true)
 8 APPPATH\Controllers\back\Admin.php(13): view('back/panel')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Admin->panel()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Admin))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 11:49:12 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/sidebar_admin.php
[Method: GET, Route: admin]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/sidebar_admin.php')
 2 SYSTEMPATH\View\View.php(475): CodeIgniter\View\View->render('layouts/sidebar_admin', null, true)
 3 APPPATH\Views\back\layouts\plantilla_admin.php(22): CodeIgniter\View\View->include('layouts/sidebar_admin')
 4 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\layouts\\plantilla_admin.php')
 5 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('back/layouts/plantilla_admin', [], true)
 7 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/panel', [], true)
 8 APPPATH\Controllers\back\Admin.php(13): view('back/panel')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Admin->panel()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Admin))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 11:49:14 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/plantilla.php
[Method: GET, Route: /]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/plantilla.php')
 2 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('layouts/plantilla', [], true)
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/principal', [], true)
 4 APPPATH\Controllers\front\Principal.php(12): view('front/principal')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Principal->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Principal))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 11:51:35 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/plantilla_admin.php
[Method: GET, Route: admin/categorias]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/plantilla_admin.php')
 2 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('layouts/plantilla_admin', [], true)
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/categorias/index', [], true)
 4 APPPATH\Controllers\back\Categorias.php(16): view('back/categorias/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Categorias->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Categorias))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 11:56:11 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/plantilla_admin.php
[Method: GET, Route: admin/categorias]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/plantilla_admin.php')
 2 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('layouts/plantilla_admin', [], true)
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/categorias/index', [], true)
 4 APPPATH\Controllers\back\Categorias.php(16): view('back/categorias/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Categorias->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Categorias))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 11:59:34 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/plantilla_admin.php
[Method: GET, Route: admin/categorias]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/plantilla_admin.php')
 2 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('layouts/plantilla_admin', [], true)
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/categorias/index', [], true)
 4 APPPATH\Controllers\back\Categorias.php(16): view('back/categorias/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Categorias->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Categorias))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 12:00:14 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/plantilla_admin.php
[Method: GET, Route: admin/categorias]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/plantilla_admin.php')
 2 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('layouts/plantilla_admin', [], true)
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/categorias/index', [], true)
 4 APPPATH\Controllers\back\Categorias.php(16): view('back/categorias/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Categorias->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Categorias))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 12:00:41 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/plantilla_admin.php
[Method: GET, Route: admin/categorias]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/plantilla_admin.php')
 2 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('layouts/plantilla_admin', [], true)
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/categorias/index', [], true)
 4 APPPATH\Controllers\back\Categorias.php(16): view('back/categorias/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Categorias->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Categorias))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 12:01:17 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/plantilla_admin.php
[Method: GET, Route: admin/categorias]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/plantilla_admin.php')
 2 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('layouts/plantilla_admin', [], true)
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/categorias/index', [], true)
 4 APPPATH\Controllers\back\Categorias.php(16): view('back/categorias/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Categorias->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Categorias))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 12:01:30 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/plantilla_admin.php
[Method: GET, Route: admin/categorias]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/plantilla_admin.php')
 2 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('layouts/plantilla_admin', [], true)
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/categorias/index', [], true)
 4 APPPATH\Controllers\back\Categorias.php(16): view('back/categorias/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Categorias->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Categorias))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 12:01:37 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/plantilla_admin.php
[Method: GET, Route: admin/categorias]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/plantilla_admin.php')
 2 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('layouts/plantilla_admin', [], true)
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/categorias/index', [], true)
 4 APPPATH\Controllers\back\Categorias.php(16): view('back/categorias/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Categorias->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Categorias))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 12:01:40 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/plantilla_admin.php
[Method: GET, Route: admin/categorias]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/plantilla_admin.php')
 2 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('layouts/plantilla_admin', [], true)
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/categorias/index', [], true)
 4 APPPATH\Controllers\back\Categorias.php(16): view('back/categorias/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Categorias->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Categorias))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 12:01:51 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/plantilla_admin.php
[Method: GET, Route: admin/categorias]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/plantilla_admin.php')
 2 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('layouts/plantilla_admin', [], true)
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/categorias/index', [], true)
 4 APPPATH\Controllers\back\Categorias.php(16): view('back/categorias/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Categorias->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Categorias))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 12:02:08 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/plantilla_admin.php
[Method: GET, Route: admin/categorias]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/plantilla_admin.php')
 2 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('layouts/plantilla_admin', [], true)
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/categorias/index', [], true)
 4 APPPATH\Controllers\back\Categorias.php(16): view('back/categorias/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Categorias->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Categorias))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 12:02:16 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: layouts/plantilla_admin.php
[Method: GET, Route: admin/categorias]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layouts/plantilla_admin.php')
 2 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('layouts/plantilla_admin', [], true)
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/categorias/index', [], true)
 4 APPPATH\Controllers\back\Categorias.php(16): view('back/categorias/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Categorias->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Categorias))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 12:05:43 --> Error: Class "App\Models\ConsultaModel" not found
[Method: GET, Route: admin/consultas]
in APPPATH\Controllers\back\Consultas.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Consultas->index()
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Consultas))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 12:07:49 --> TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given
[Method: GET, Route: admin/consultas]
in APPPATH\Views\back\categorias\index.php on line 29.
 1 SYSTEMPATH\View\View.php(224): include()
 2 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/categorias/index', [], true)
 4 APPPATH\Controllers\back\Consultas.php(15): view('back/categorias/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Consultas->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Consultas))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 12:07:49 --> [Caused by] ErrorException: Undefined variable $categorias
in APPPATH\Views\back\categorias\index.php on line 29.
 1 APPPATH\Views\back\categorias\index.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $categorias', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\categorias\\index.php', 29)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\categorias\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/categorias/index', [], true)
 5 APPPATH\Controllers\back\Consultas.php(15): view('back/categorias/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Consultas->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Consultas))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 13:28:34 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: front/consulta.php
[Method: GET, Route: consulta]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('front/consulta.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consulta', [], true)
 3 APPPATH\Controllers\front\Consulta.php(10): view('front/consultas')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 13:29:03 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: front/consultas/index.php
[Method: GET, Route: consulta]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('front/consultas/index.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consultas/index', [], true)
 3 APPPATH\Controllers\front\Consulta.php(10): view('front/consultass/index')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 13:41:31 --> ErrorException: Undefined array key "titulo"
[Method: GET, Route: consulta]
in APPPATH\Views\front\consulta\index.php on line 28.
 1 APPPATH\Views\front\consulta\index.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titulo"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php', 28)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consulta/index', [], true)
 5 APPPATH\Controllers\front\Consulta.php(17): view('front/consultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 13:43:29 --> ErrorException: Undefined array key "titulo"
[Method: GET, Route: consulta]
in APPPATH\Views\front\consulta\index.php on line 28.
 1 APPPATH\Views\front\consulta\index.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titulo"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php', 28)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consulta/index', [], true)
 5 APPPATH\Controllers\front\Consulta.php(17): view('front/consultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 13:43:35 --> ErrorException: Undefined array key "titulo"
[Method: GET, Route: consulta]
in APPPATH\Views\front\consulta\index.php on line 28.
 1 APPPATH\Views\front\consulta\index.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titulo"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php', 28)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consulta/index', [], true)
 5 APPPATH\Controllers\front\Consulta.php(17): view('front/consultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 13:43:41 --> ErrorException: Undefined array key "titulo"
[Method: GET, Route: consulta]
in APPPATH\Views\front\consulta\index.php on line 28.
 1 APPPATH\Views\front\consulta\index.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titulo"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php', 28)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consulta/index', [], true)
 5 APPPATH\Controllers\front\Consulta.php(17): view('front/consultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 13:43:59 --> ErrorException: Undefined array key "titulo"
[Method: GET, Route: consulta]
in APPPATH\Views\front\consulta\index.php on line 28.
 1 APPPATH\Views\front\consulta\index.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titulo"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php', 28)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consulta/index', [], true)
 5 APPPATH\Controllers\front\Consulta.php(17): view('front/consultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 13:44:09 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: front/consultas/index.php
[Method: GET, Route: consulta]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('front/consultas/index.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consultas/index', [], true)
 3 APPPATH\Controllers\front\Consulta.php(17): view('front/consultass/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 13:47:15 --> ErrorException: Undefined array key "titulo"
[Method: GET, Route: consulta]
in APPPATH\Views\front\consulta\index.php on line 28.
 1 APPPATH\Views\front\consulta\index.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titulo"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php', 28)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consulta/index', [], true)
 5 APPPATH\Controllers\front\Consulta.php(17): view('front/consultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 13:47:21 --> ErrorException: Undefined array key "titulo"
[Method: GET, Route: consulta]
in APPPATH\Views\front\consulta\index.php on line 28.
 1 APPPATH\Views\front\consulta\index.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titulo"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php', 28)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consulta/index', [], true)
 5 APPPATH\Controllers\front\Consulta.php(17): view('front/consultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 13:47:26 --> ErrorException: Undefined array key "titulo"
[Method: GET, Route: consulta]
in APPPATH\Views\front\consulta\index.php on line 28.
 1 APPPATH\Views\front\consulta\index.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titulo"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php', 28)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consulta/index', [], true)
 5 APPPATH\Controllers\front\Consulta.php(17): view('front/consultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 13:47:34 --> ErrorException: Undefined array key "titulo"
[Method: GET, Route: consulta]
in APPPATH\Views\front\consulta\index.php on line 28.
 1 APPPATH\Views\front\consulta\index.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titulo"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php', 28)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consulta/index', [], true)
 5 APPPATH\Controllers\front\Consulta.php(17): view('front/consultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 13:47:45 --> ErrorException: Undefined array key "titulo"
[Method: GET, Route: consulta]
in APPPATH\Views\front\consulta\index.php on line 28.
 1 APPPATH\Views\front\consulta\index.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titulo"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php', 28)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consulta/index', [], true)
 5 APPPATH\Controllers\front\Consulta.php(17): view('front/consultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 13:59:16 --> ErrorException: Undefined array key "titulo"
[Method: GET, Route: consulta/ver/1]
in APPPATH\Views\front\consulta\ver.php on line 9.
 1 APPPATH\Views\front\consulta\ver.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titulo"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\ver.php', 9)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consulta/ver', [], true)
 5 APPPATH\Controllers\front\Consulta.php(60): view('front/consultas/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 13:59:50 --> ErrorException: Undefined array key "titulo"
[Method: GET, Route: consulta/ver/1]
in APPPATH\Views\front\consulta\ver.php on line 9.
 1 APPPATH\Views\front\consulta\ver.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titulo"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\ver.php', 9)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consulta/ver', [], true)
 5 APPPATH\Controllers\front\Consulta.php(60): view('front/consultas/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 14:00:11 --> ErrorException: Undefined variable $mensajes
[Method: GET, Route: consulta/ver/1]
in APPPATH\Views\front\consulta\ver.php on line 13.
 1 APPPATH\Views\front\consulta\ver.php(13): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $mensajes', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\ver.php', 13)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consulta\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consulta/ver', [], true)
 5 APPPATH\Controllers\front\Consulta.php(60): view('front/consultas/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-21 15:15:21 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Consulta.php(72): CodeIgniter\Model->insert(Array)
#8 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
#9 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
#10 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-21 15:15:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: consultas/responder/1]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (:consulta_id:, :usuario_id:, :mensaje:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\front\Consulta.php(72): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 15:15:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'asdfasdfasdf\', \'2025-06-21 15:15:21\', \'2025-06-21 15:15:21\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'asdfasdfasdf\', \'2025-06-21 15:15:21\', \'2025-06-21 15:15:21\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (:consulta_id:, :usuario_id:, :mensaje:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\front\Consulta.php(72): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 15:15:22 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'asdfasdfasdf\', \'2025-06-21 15:15:21\', \'2025-06-21 15:15:21\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'asdfasdfasdf\', \'2025-06-21 15:15:21\', \'2025-06-21 15:15:21\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'asdfasdfasdf\', \'2025-06-21 15:15:21\', \'2025-06-21 15:15:21\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (:consulta_id:, :usuario_id:, :mensaje:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\front\Consulta.php(72): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-21 15:16:34 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Consulta.php(71): CodeIgniter\Model->insert(Array)
#8 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
#9 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
#10 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-21 15:16:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: consultas/responder/1]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (:consulta_id:, :usuario_id:, :mensaje:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\front\Consulta.php(71): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 15:16:35 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'asdfasdfasdf\', \'2025-06-21 15:16:34\', \'2025-06-21 15:16:34\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'asdfasdfasdf\', \'2025-06-21 15:16:34\', \'2025-06-21 15:16:34\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (:consulta_id:, :usuario_id:, :mensaje:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\front\Consulta.php(71): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 15:16:35 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'asdfasdfasdf\', \'2025-06-21 15:16:34\', \'2025-06-21 15:16:34\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'asdfasdfasdf\', \'2025-06-21 15:16:34\', \'2025-06-21 15:16:34\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'asdfasdfasdf\', \'2025-06-21 15:16:34\', \'2025-06-21 15:16:34\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (:consulta_id:, :usuario_id:, :mensaje:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\front\Consulta.php(71): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-21 15:17:02 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Consulta.php(71): CodeIgniter\Model->insert(Array)
#8 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
#9 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
#10 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-21 15:17:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: consultas/responder/1]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (:consulta_id:, :usuario_id:, :mensaje:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\front\Consulta.php(71): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 15:17:02 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'asdfasdfasdfasdf\', \'2025-06-21 15:17:02\', \'2025-06-21 15:17:02\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'asdfasdfasdfasdf\', \'2025-06-21 15:17:02\', \'2025-06-21 15:17:02\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (:consulta_id:, :usuario_id:, :mensaje:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\front\Consulta.php(71): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 15:17:02 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'asdfasdfasdfasdf\', \'2025-06-21 15:17:02\', \'2025-06-21 15:17:02\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'asdfasdfasdfasdf\', \'2025-06-21 15:17:02\', \'2025-06-21 15:17:02\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'asdfasdfasdfasdf\', \'2025-06-21 15:17:02\', \'2025-06-21 15:17:02\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (:consulta_id:, :usuario_id:, :mensaje:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\front\Consulta.php(71): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-21 15:17:59 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Consulta.php(71): CodeIgniter\Model->insert(Array)
#8 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
#9 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
#10 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-21 15:17:59 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: consultas/responder/1]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (:consulta_id:, :usuario_id:, :mensaje:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\front\Consulta.php(71): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 15:17:59 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'fdgsdfgsdfgsdfg\', \'2025-06-21 15:17:59\', \'2025-06-21 15:17:59\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'fdgsdfgsdfgsdfg\', \'2025-06-21 15:17:59\', \'2025-06-21 15:17:59\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (:consulta_id:, :usuario_id:, :mensaje:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\front\Consulta.php(71): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 15:17:59 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'fdgsdfgsdfgsdfg\', \'2025-06-21 15:17:59\', \'2025-06-21 15:17:59\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'fdgsdfgsdfgsdfg\', \'2025-06-21 15:17:59\', \'2025-06-21 15:17:59\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (\'1\', \'7\', \'fdgsdfgsdfgsdfg\', \'2025-06-21 15:17:59\', \'2025-06-21 15:17:59\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `consultas_mensajes` (`consulta_id`, `usuario_id`, `mensaje`, `created_at`, `updated_at`) VALUES (:consulta_id:, :usuario_id:, :mensaje:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\front\Consulta.php(71): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-21 15:20:09 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Consulta.php(71): CodeIgniter\Model->insert(Array)
#8 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Consulta->responderPost('1')
#9 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
#10 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-21 15:30:50 --> TypeError: Cannot access offset of type string on string
[Method: GET, Route: consultas/ver/1]
in APPPATH\Views\front\consultas\ver.php on line 25.
 1 SYSTEMPATH\View\View.php(224): include()
 2 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consultas/ver', [], true)
 4 APPPATH\Controllers\front\Consulta.php(63): view('front/consultas/ver', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->ver('1')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 15:30:54 --> ErrorException: Array to string conversion
[Method: GET, Route: consultas/ver/1]
in APPPATH\Views\front\consultas\ver.php on line 25.
 1 APPPATH\Views\front\consultas\ver.php(25): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consultas\\ver.php', 25)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\consultas\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consultas/ver', [], true)
 5 APPPATH\Controllers\front\Consulta.php(63): view('front/consultas/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 15:31:08 --> TypeError: Cannot access offset of type string on string
[Method: GET, Route: consultas/ver/1]
in APPPATH\Views\front\consultas\ver.php on line 25.
 1 SYSTEMPATH\View\View.php(224): include()
 2 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/consultas/ver', [], true)
 4 APPPATH\Controllers\front\Consulta.php(63): view('front/consultas/ver', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Consulta->ver('1')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Consulta))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 16:14:20 --> CodeIgniter\Database\Exceptions\DataException: No hay datos para insert
[Method: POST, Route: contacto/enviar]
in SYSTEMPATH\BaseModel.php on line 825.
 1 SYSTEMPATH\BaseModel.php(825): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([], true)
 3 APPPATH\Controllers\front\Contacto.php(21): CodeIgniter\Model->insert([...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Contacto->enviar()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Contacto))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 16:15:16 --> CodeIgniter\Database\Exceptions\DataException: No hay datos para insert
[Method: POST, Route: contacto/enviar]
in SYSTEMPATH\BaseModel.php on line 825.
 1 SYSTEMPATH\BaseModel.php(825): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([], true)
 3 APPPATH\Controllers\front\Contacto.php(20): CodeIgniter\Model->insert([...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Contacto->enviar()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Contacto))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 16:26:21 --> ErrorException: Undefined array key "nombre"
[Method: GET, Route: admin/consultas]
in APPPATH\Views\back\consultas\index.php on line 38.
 1 APPPATH\Views\back\consultas\index.php(38): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "nombre"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\index.php', 38)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/consultas/index', [], true)
 5 APPPATH\Controllers\back\Consultas.php(15): view('back/consultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Consultas->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Consultas))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 17:14:50 --> ErrorException: Undefined array key "titulo"
[Method: GET, Route: admin/consultas]
in APPPATH\Views\back\consultas\index.php on line 39.
 1 APPPATH\Views\back\consultas\index.php(39): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titulo"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\index.php', 39)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/consultas/index', [], true)
 5 APPPATH\Controllers\back\Consultas.php(20): view('back/consultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Consultas->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Consultas))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 17:16:08 --> ErrorException: Undefined array key "titulo"
[Method: GET, Route: admin/consultas]
in APPPATH\Views\back\consultas\index.php on line 39.
 1 APPPATH\Views\back\consultas\index.php(39): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titulo"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\index.php', 39)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/consultas/index', [], true)
 5 APPPATH\Controllers\back\Consultas.php(20): view('back/consultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Consultas->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Consultas))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 17:16:11 --> ErrorException: Undefined array key "titulo"
[Method: GET, Route: admin/consultas]
in APPPATH\Views\back\consultas\index.php on line 39.
 1 APPPATH\Views\back\consultas\index.php(39): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "titulo"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\index.php', 39)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/consultas/index', [], true)
 5 APPPATH\Controllers\back\Consultas.php(20): view('back/consultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Consultas->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Consultas))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 17:20:37 --> CodeIgniter\View\Exceptions\ViewException: Archivo inválido: back/consultas/ver.php
[Method: GET, Route: admin/consultas/ver/1]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('back/consultas/ver.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/consultas/ver', [], true)
 3 APPPATH\Controllers\back\Consultas.php(33): view('back/consultas/ver', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Consultas->ver('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Consultas))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 17:23:20 --> ErrorException: Undefined variable $consultas
[Method: GET, Route: admin/consultas/ver/1]
in APPPATH\Views\back\consultas\ver.php on line 31.
 1 APPPATH\Views\back\consultas\ver.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $consultas', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\ver.php', 31)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/consultas/ver', [], true)
 5 APPPATH\Controllers\back\Consultas.php(33): view('back/consultas/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Consultas->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Consultas))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 17:23:43 --> ErrorException: Undefined array key "nombre"
[Method: GET, Route: admin/consultas/ver/1]
in APPPATH\Views\back\consultas\ver.php on line 31.
 1 APPPATH\Views\back\consultas\ver.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "nombre"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\ver.php', 31)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/consultas/ver', [], true)
 5 APPPATH\Controllers\back\Consultas.php(33): view('back/consultas/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Consultas->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Consultas))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 17:23:48 --> ErrorException: Undefined array key "nombre"
[Method: GET, Route: admin/consultas/ver/1]
in APPPATH\Views\back\consultas\ver.php on line 31.
 1 APPPATH\Views\back\consultas\ver.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "nombre"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\ver.php', 31)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/consultas/ver', [], true)
 5 APPPATH\Controllers\back\Consultas.php(33): view('back/consultas/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Consultas->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Consultas))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 17:24:00 --> ErrorException: Undefined array key "nombre"
[Method: GET, Route: admin/consultas/ver/1]
in APPPATH\Views\back\consultas\ver.php on line 31.
 1 APPPATH\Views\back\consultas\ver.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "nombre"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\ver.php', 31)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/consultas/ver', [], true)
 5 APPPATH\Controllers\back\Consultas.php(33): view('back/consultas/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Consultas->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Consultas))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 17:24:52 --> ErrorException: Undefined array key "nombre"
[Method: GET, Route: admin/consultas/ver/1]
in APPPATH\Views\back\consultas\ver.php on line 20.
 1 APPPATH\Views\back\consultas\ver.php(20): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "nombre"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\ver.php', 20)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/consultas/ver', [], true)
 5 APPPATH\Controllers\back\Consultas.php(33): view('back/consultas/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Consultas->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Consultas))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 17:41:18 --> ErrorException: Undefined array key "nombre"
[Method: GET, Route: admin/consultas/ver/1]
in APPPATH\Views\back\consultas\ver.php on line 45.
 1 APPPATH\Views\back\consultas\ver.php(45): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "nombre"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\ver.php', 45)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/consultas/ver', [], true)
 5 APPPATH\Controllers\back\Consultas.php(45): view('back/consultas/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Consultas->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Consultas))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 17:49:39 --> ErrorException: Undefined variable $contactos
[Method: GET, Route: admin/contactos]
in APPPATH\Views\back\contactos\index.php on line 31.
 1 APPPATH\Views\back\contactos\index.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $contactos', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\contactos\\index.php', 31)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\contactos\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/contactos/index', [], true)
 5 APPPATH\Controllers\back\Contactos.php(15): view('back/contactos/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Contactos->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Contactos))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 17:50:36 --> ErrorException: Undefined variable $contactos
[Method: GET, Route: admin/contactos]
in APPPATH\Views\back\contactos\index.php on line 31.
 1 APPPATH\Views\back\contactos\index.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $contactos', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\contactos\\index.php', 31)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\contactos\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/contactos/index', [], true)
 5 APPPATH\Controllers\back\Contactos.php(15): view('back/contactos/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Contactos->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Contactos))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 17:53:06 --> ErrorException: Undefined variable $consulta
[Method: GET, Route: admin/contactos/ver/1]
in APPPATH\Views\back\contactos\ver.php on line 20.
 1 APPPATH\Views\back\contactos\ver.php(20): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $consulta', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\contactos\\ver.php', 20)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\contactos\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/contactos/ver', [], true)
 5 APPPATH\Controllers\back\Contactos.php(29): view('back/contactos/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Contactos->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Contactos))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 17:53:18 --> ErrorException: Undefined array key "apellido"
[Method: GET, Route: admin/contactos/ver/1]
in APPPATH\Views\back\contactos\ver.php on line 20.
 1 APPPATH\Views\back\contactos\ver.php(20): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "apellido"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\contactos\\ver.php', 20)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\contactos\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/contactos/ver', [], true)
 5 APPPATH\Controllers\back\Contactos.php(29): view('back/contactos/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Contactos->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Contactos))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 17:53:43 --> ErrorException: Undefined array key "apellido"
[Method: GET, Route: admin/contactos/ver/1]
in APPPATH\Views\back\contactos\ver.php on line 21.
 1 APPPATH\Views\back\contactos\ver.php(21): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "apellido"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\contactos\\ver.php', 21)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\contactos\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/contactos/ver', [], true)
 5 APPPATH\Controllers\back\Contactos.php(29): view('back/contactos/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Contactos->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Contactos))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 18:16:03 --> ErrorException: Undefined variable $contacto
[Method: GET, Route: admin/consultas/ver/1]
in APPPATH\Views\back\consultas\ver.php on line 33.
 1 APPPATH\Views\back\consultas\ver.php(33): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $contacto', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\ver.php', 33)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\back\\consultas\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('back/consultas/ver', [], true)
 5 APPPATH\Controllers\back\Consultas.php(44): view('back/consultas/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\back\Consultas->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\back\Consultas))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-21 18:49:14 --> mysqli_sql_exception: Unknown column 'carrito_items.deleted_at' in 'where clause' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#6 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Carrito.php(43): CodeIgniter\BaseModel->first()
#7 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Carrito->agregar('7')
#8 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
#9 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-06-21 18:49:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'carrito_items.deleted_at' in 'where clause'
[Method: POST, Route: carrito/agregar/7]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = :usuario_id:
AND `producto_id` = :producto_id:
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\front\Carrito.php(43): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Carrito->agregar('7')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 18:49:14 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'carrito_items.deleted_at' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = \'7\'
AND `producto_id` = \'7\'
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = \'7\'
AND `producto_id` = \'7\'
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = :usuario_id:
AND `producto_id` = :producto_id:
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 6 APPPATH\Controllers\front\Carrito.php(43): CodeIgniter\BaseModel->first()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Carrito->agregar('7')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 18:49:14 --> [Caused by] mysqli_sql_exception: Unknown column 'carrito_items.deleted_at' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = \'7\'
AND `producto_id` = \'7\'
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = \'7\'
AND `producto_id` = \'7\'
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = \'7\'
AND `producto_id` = \'7\'
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = :usuario_id:
AND `producto_id` = :producto_id:
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 7 APPPATH\Controllers\front\Carrito.php(43): CodeIgniter\BaseModel->first()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Carrito->agregar('7')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-21 19:25:05 --> mysqli_sql_exception: Unknown column 'carrito_items.deleted_at' in 'where clause' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#6 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Carrito.php(43): CodeIgniter\BaseModel->first()
#7 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Carrito->agregar('7')
#8 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
#9 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-06-21 19:25:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'carrito_items.deleted_at' in 'where clause'
[Method: POST, Route: carrito/agregar/7]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = :usuario_id:
AND `producto_id` = :producto_id:
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\front\Carrito.php(43): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Carrito->agregar('7')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 19:25:06 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'carrito_items.deleted_at' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = \'7\'
AND `producto_id` = \'7\'
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = \'7\'
AND `producto_id` = \'7\'
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = :usuario_id:
AND `producto_id` = :producto_id:
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 6 APPPATH\Controllers\front\Carrito.php(43): CodeIgniter\BaseModel->first()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Carrito->agregar('7')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 19:25:06 --> [Caused by] mysqli_sql_exception: Unknown column 'carrito_items.deleted_at' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = \'7\'
AND `producto_id` = \'7\'
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = \'7\'
AND `producto_id` = \'7\'
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = \'7\'
AND `producto_id` = \'7\'
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = :usuario_id:
AND `producto_id` = :producto_id:
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 7 APPPATH\Controllers\front\Carrito.php(43): CodeIgniter\BaseModel->first()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Carrito->agregar('7')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-21 19:26:32 --> mysqli_sql_exception: Unknown column 'carrito_items.deleted_at' in 'where clause' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#6 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Carrito.php(43): CodeIgniter\BaseModel->first()
#7 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Carrito->agregar('7')
#8 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
#9 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-06-21 19:26:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'carrito_items.deleted_at' in 'where clause'
[Method: POST, Route: carrito/agregar/7]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = :usuario_id:
AND `producto_id` = :producto_id:
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\front\Carrito.php(43): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Carrito->agregar('7')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 19:26:32 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'carrito_items.deleted_at' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = \'7\'
AND `producto_id` = \'7\'
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = \'7\'
AND `producto_id` = \'7\'
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = :usuario_id:
AND `producto_id` = :producto_id:
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 6 APPPATH\Controllers\front\Carrito.php(43): CodeIgniter\BaseModel->first()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Carrito->agregar('7')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 19:26:32 --> [Caused by] mysqli_sql_exception: Unknown column 'carrito_items.deleted_at' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = \'7\'
AND `producto_id` = \'7\'
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = \'7\'
AND `producto_id` = \'7\'
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = \'7\'
AND `producto_id` = \'7\'
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `carrito_items`
WHERE `usuario_id` = :usuario_id:
AND `producto_id` = :producto_id:
AND `carrito_items`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 7 APPPATH\Controllers\front\Carrito.php(43): CodeIgniter\BaseModel->first()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Carrito->agregar('7')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-21 19:26:54 --> mysqli_sql_exception: Unknown column 'carrito_items.deleted_at' in 'where clause' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#6 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Carrito.php(43): CodeIgniter\BaseModel->first()
#7 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Carrito->agregar('7')
#8 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
#9 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-06-21 20:39:36 --> ErrorException: Undefined array key "fecha"
[Method: GET, Route: pedidos]
in APPPATH\Views\front\pedidos\index.php on line 28.
 1 APPPATH\Views\front\pedidos\index.php(28): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "fecha"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\pedidos\\index.php', 28)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\pedidos\\index.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/pedidos/index', [], true)
 5 APPPATH\Controllers\front\Pedido.php(16): view('front/pedidos/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 20:52:58 --> ErrorException: Undefined array key "precio"
[Method: GET, Route: pedidos/ver/1]
in APPPATH\Views\front\pedidos\ver.php on line 35.
 1 APPPATH\Views\front\pedidos\ver.php(35): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "precio"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\pedidos\\ver.php', 35)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\pedidos\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/pedidos/ver', [], true)
 5 APPPATH\Controllers\front\Pedido.php(38): view('front/pedidos/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 20:54:12 --> ErrorException: Undefined array key "precio"
[Method: GET, Route: pedidos/ver/1]
in APPPATH\Views\front\pedidos\ver.php on line 35.
 1 APPPATH\Views\front\pedidos\ver.php(35): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "precio"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\pedidos\\ver.php', 35)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\pedidos\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/pedidos/ver', [], true)
 5 APPPATH\Controllers\front\Pedido.php(38): view('front/pedidos/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 20:54:21 --> ErrorException: Undefined array key "nombre"
[Method: GET, Route: pedidos/ver/1]
in APPPATH\Views\front\pedidos\ver.php on line 37.
 1 APPPATH\Views\front\pedidos\ver.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "nombre"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\pedidos\\ver.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\pedidos\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/pedidos/ver', [], true)
 5 APPPATH\Controllers\front\Pedido.php(38): view('front/pedidos/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 20:55:28 --> ErrorException: Undefined array key "nombre"
[Method: GET, Route: pedidos/ver/1]
in APPPATH\Views\front\pedidos\ver.php on line 37.
 1 APPPATH\Views\front\pedidos\ver.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "nombre"', 'E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\pedidos\\ver.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\front\\pedidos\\ver.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/pedidos/ver', [], true)
 5 APPPATH\Controllers\front\Pedido.php(38): view('front/pedidos/ver', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('1')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-21 20:59:32 --> mysqli_sql_exception: Duplicate entry '7' for key 'fk_pedidos_usuarios' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `pe...', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Carrito.php(104): CodeIgniter\Model->insert(Array)
#8 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Carrito->comprar()
#9 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
#10 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-21 20:59:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '7' for key 'fk_pedidos_usuarios'
[Method: POST, Route: carrito/comprar]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pedidos` (`usuario_id`, `direccion_envio`, `estado`, `total`, `created_at`, `updated_at`) VALUES (:usuario_id:, :direccion_envio:, :estado:, :total:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\front\Carrito.php(104): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Carrito->comprar()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 20:59:32 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '7' for key 'fk_pedidos_usuarios'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pedidos` (`usuario_id`, `direccion_envio`, `estado`, `total`, `created_at`, `updated_at`) VALUES (\'7\', \'\', \'pendiente\', 1000000, \'2025-06-21 20:59:32\', \'2025-06-21 20:59:32\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pedidos` (`usuario_id`, `direccion_envio`, `estado`, `total`, `created_at`, `updated_at`) VALUES (\'7\', \'\', \'pendiente\', 1000000, \'2025-06-21 20:59:32\', \'2025-06-21 20:59:32\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pedidos` (`usuario_id`, `direccion_envio`, `estado`, `total`, `created_at`, `updated_at`) VALUES (:usuario_id:, :direccion_envio:, :estado:, :total:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\front\Carrito.php(104): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Carrito->comprar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-21 20:59:32 --> [Caused by] mysqli_sql_exception: Duplicate entry '7' for key 'fk_pedidos_usuarios'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `pedidos` (`usuario_id`, `direccion_envio`, `estado`, `total`, `created_at`, `updated_at`) VALUES (\'7\', \'\', \'pendiente\', 1000000, \'2025-06-21 20:59:32\', \'2025-06-21 20:59:32\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pedidos` (`usuario_id`, `direccion_envio`, `estado`, `total`, `created_at`, `updated_at`) VALUES (\'7\', \'\', \'pendiente\', 1000000, \'2025-06-21 20:59:32\', \'2025-06-21 20:59:32\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pedidos` (`usuario_id`, `direccion_envio`, `estado`, `total`, `created_at`, `updated_at`) VALUES (\'7\', \'\', \'pendiente\', 1000000, \'2025-06-21 20:59:32\', \'2025-06-21 20:59:32\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pedidos` (`usuario_id`, `direccion_envio`, `estado`, `total`, `created_at`, `updated_at`) VALUES (:usuario_id:, :direccion_envio:, :estado:, :total:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\front\Carrito.php(104): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Carrito->comprar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-21 21:00:50 --> mysqli_sql_exception: Duplicate entry '7' for key 'fk_pedidos_usuarios' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `pe...', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Carrito.php(104): CodeIgniter\Model->insert(Array)
#8 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Carrito->comprar()
#9 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
#10 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
