ERROR - 2025-06-30 17:39:19 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'zonahw' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'zonahw', 3306, '', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\Proyecto-TPI\app\Views\layouts\front\header.php(206): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\Proyecto-TPI\system\View\View.php(224): include('E:\\xampp\\htdocs...')
#8 E:\xampp\htdocs\Proyecto-TPI\system\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#9 E:\xampp\htdocs\Proyecto-TPI\system\View\View.php(475): CodeIgniter\View\View->render('layouts/front/h...', NULL, true)
#10 E:\xampp\htdocs\Proyecto-TPI\app\Views\layouts\front\plantilla.php(25): CodeIgniter\View\View->include('layouts/front/h...')
#11 E:\xampp\htdocs\Proyecto-TPI\system\View\View.php(224): include('E:\\xampp\\htdocs...')
#12 E:\xampp\htdocs\Proyecto-TPI\system\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#13 E:\xampp\htdocs\Proyecto-TPI\system\View\View.php(240): CodeIgniter\View\View->render('layouts/front/p...', Array, true)
#14 E:\xampp\htdocs\Proyecto-TPI\system\Common.php(1173): CodeIgniter\View\View->render('front/principal', Array, true)
#15 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Principal.php(12): view('front/principal')
#16 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Principal->index()
#17 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Principal))
#18 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#19 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#20 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#21 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#22 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'zonahw' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\Proyecto-TPI\app\Views\layouts\front\header.php(206): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\Proyecto-TPI\system\View\View.php(224): include('E:\\xampp\\htdocs...')
#7 E:\xampp\htdocs\Proyecto-TPI\system\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#8 E:\xampp\htdocs\Proyecto-TPI\system\View\View.php(475): CodeIgniter\View\View->render('layouts/front/h...', NULL, true)
#9 E:\xampp\htdocs\Proyecto-TPI\app\Views\layouts\front\plantilla.php(25): CodeIgniter\View\View->include('layouts/front/h...')
#10 E:\xampp\htdocs\Proyecto-TPI\system\View\View.php(224): include('E:\\xampp\\htdocs...')
#11 E:\xampp\htdocs\Proyecto-TPI\system\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#12 E:\xampp\htdocs\Proyecto-TPI\system\View\View.php(240): CodeIgniter\View\View->render('layouts/front/p...', Array, true)
#13 E:\xampp\htdocs\Proyecto-TPI\system\Common.php(1173): CodeIgniter\View\View->render('front/principal', Array, true)
#14 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Principal.php(12): view('front/principal')
#15 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Principal->index()
#16 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Principal))
#17 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#18 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#19 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#20 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#21 {main}
CRITICAL - 2025-06-30 17:39:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'zonahw'
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `categorias`
WHERE `categorias`.`deleted_at` IS NULL', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Views\layouts\front\header.php(206): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\layouts\\front\\header.php')
 7 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\View\View.php(475): CodeIgniter\View\View->render('layouts/front/header', null, true)
 9 APPPATH\Views\layouts\front\plantilla.php(25): CodeIgniter\View\View->include('layouts/front/header')
10 SYSTEMPATH\View\View.php(224): include('E:\\xampp\\htdocs\\Proyecto-TPI\\app\\Views\\layouts\\front\\plantilla.php')
11 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
12 SYSTEMPATH\View\View.php(240): CodeIgniter\View\View->render('layouts/front/plantilla', [], true)
13 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('front/principal', [], true)
14 APPPATH\Controllers\front\Principal.php(12): view('front/principal')
15 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Principal->index()
16 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Principal))
17 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
18 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
19 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
20 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-30 18:48:55 --> mysqli_sql_exception: Unknown column 'usuarios.direccion' in 'field list' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `pedidos...', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `pedidos...')
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `pedidos...')
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#6 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
#7 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
#8 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
#9 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-06-30 18:48:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'usuarios.direccion' in 'field list'
[Method: GET, Route: pedidos/ver/5]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = :pedidos.id:
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-30 18:48:56 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'usuarios.direccion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = :pedidos.id:
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 6 APPPATH\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-30 18:48:56 --> [Caused by] mysqli_sql_exception: Unknown column 'usuarios.direccion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = :pedidos.id:
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 7 APPPATH\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-30 18:50:17 --> mysqli_sql_exception: Unknown column 'usuarios.direccion' in 'field list' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `pedidos...', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `pedidos...')
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `pedidos...')
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#6 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
#7 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
#8 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
#9 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-06-30 18:50:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'usuarios.direccion' in 'field list'
[Method: GET, Route: pedidos/ver/5]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = :pedidos.id:
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-30 18:50:18 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'usuarios.direccion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = :pedidos.id:
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 6 APPPATH\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-30 18:50:18 --> [Caused by] mysqli_sql_exception: Unknown column 'usuarios.direccion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = :pedidos.id:
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 7 APPPATH\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-30 18:50:50 --> mysqli_sql_exception: Unknown column 'usuarios.direccion' in 'field list' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `pedidos...', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `pedidos...')
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `pedidos...')
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#6 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
#7 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
#8 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
#9 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-06-30 18:50:50 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'usuarios.direccion' in 'field list'
[Method: GET, Route: pedidos/ver/5]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = :pedidos.id:
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-30 18:50:50 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'usuarios.direccion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = :pedidos.id:
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 6 APPPATH\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-30 18:50:50 --> [Caused by] mysqli_sql_exception: Unknown column 'usuarios.direccion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = :pedidos.id:
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 7 APPPATH\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-30 18:51:13 --> mysqli_sql_exception: Unknown column 'usuarios.direccion' in 'field list' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `pedidos...', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `pedidos...')
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `pedidos...')
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#6 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
#7 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
#8 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
#9 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-06-30 18:51:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'usuarios.direccion' in 'field list'
[Method: GET, Route: pedidos/ver/5]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = :pedidos.id:
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-30 18:51:14 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'usuarios.direccion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = :pedidos.id:
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 6 APPPATH\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-30 18:51:14 --> [Caused by] mysqli_sql_exception: Unknown column 'usuarios.direccion' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = \'5\'
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos`.*, `usuarios`.`nombre` as `usuario_nombre`, `usuarios`.`apellido` as `usuario_apellido`, `usuarios`.`email` as `usuario_email`, `usuarios`.`direccion` as `usuario_direccion`
FROM `pedidos`
JOIN `usuarios` ON `usuarios`.`id` = `pedidos`.`usuario_id`
WHERE `pedidos`.`id` = :pedidos.id:
AND `pedidos`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 7 APPPATH\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-30 18:51:33 --> mysqli_sql_exception: Unknown column 'usuarios.direccion' in 'field list' in E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 E:\xampp\htdocs\Proyecto-TPI\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `pedidos...', 0)
#1 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `pedidos...')
#2 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `pedidos...')
#3 E:\xampp\htdocs\Proyecto-TPI\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `pedidos...', Array, false)
#4 E:\xampp\htdocs\Proyecto-TPI\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\Proyecto-TPI\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#6 E:\xampp\htdocs\Proyecto-TPI\app\Controllers\front\Pedido.php(31): CodeIgniter\BaseModel->first()
#7 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(933): App\Controllers\front\Pedido->ver('5')
#8 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
#9 E:\xampp\htdocs\Proyecto-TPI\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\Proyecto-TPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 E:\xampp\htdocs\Proyecto-TPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-06-30 19:32:26 --> CodeIgniter\Exceptions\BadMethodCallException: Call to undefined method App\Models\PedidoModel::crearPedido
[Method: POST, Route: carrito/comprar]
in SYSTEMPATH\Model.php on line 930.
 1 APPPATH\Controllers\front\Carrito.php(100): CodeIgniter\Model->__call('crearPedido', [...])
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Carrito->comprar()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-30 19:35:47 --> CodeIgniter\Exceptions\BadMethodCallException: Call to undefined method App\Models\PedidoModel::crearPedido
[Method: POST, Route: carrito/comprar]
in SYSTEMPATH\Model.php on line 930.
 1 APPPATH\Controllers\front\Carrito.php(100): CodeIgniter\Model->__call('crearPedido', [...])
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Carrito->comprar()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-30 19:42:50 --> CodeIgniter\Exceptions\BadMethodCallException: Call to undefined method App\Models\PedidoModel::crearPedido
[Method: POST, Route: carrito/comprar]
in SYSTEMPATH\Model.php on line 930.
 1 APPPATH\Controllers\front\Carrito.php(99): CodeIgniter\Model->__call('crearPedido', [...])
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Carrito->comprar()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Carrito))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-30 19:53:38 --> TypeError: Cannot access offset of type string on string
[Method: POST, Route: pedidos/generar/7]
in APPPATH\Models\PedidoModel.php on line 38.
 1 APPPATH\Controllers\front\Pedido.php(68): App\Models\PedidoModel->crearPedido('9', [...])
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->generar('7')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-30 19:53:56 --> TypeError: Cannot access offset of type string on string
[Method: POST, Route: pedidos/generar/7]
in APPPATH\Models\PedidoModel.php on line 38.
 1 APPPATH\Controllers\front\Pedido.php(68): App\Models\PedidoModel->crearPedido('9', [...])
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\front\Pedido->generar('7')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\front\Pedido))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-30 21:14:10 --> CodeIgniter\Filters\Exceptions\FilterException: El filtro no_sesion debe tener un alias coincidente definido.
[Method: GET, Route: login]
in SYSTEMPATH\Filters\Filters.php on line 590.
 1 SYSTEMPATH\Filters\Filters.php(590): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('no_sesion')
 2 SYSTEMPATH\Filters\Filters.php(641): CodeIgniter\Filters\Filters->enableFilter('no_sesion', 'before')
 3 SYSTEMPATH\CodeIgniter.php(467): CodeIgniter\Filters\Filters->enableFilters([...], 'before')
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-30 21:14:44 --> CodeIgniter\Filters\Exceptions\FilterException: El filtro no_sesion debe tener un alias coincidente definido.
[Method: GET, Route: login]
in SYSTEMPATH\Filters\Filters.php on line 590.
 1 SYSTEMPATH\Filters\Filters.php(590): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('no_sesion')
 2 SYSTEMPATH\Filters\Filters.php(641): CodeIgniter\Filters\Filters->enableFilter('no_sesion', 'before')
 3 SYSTEMPATH\CodeIgniter.php(467): CodeIgniter\Filters\Filters->enableFilters([...], 'before')
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-30 21:15:06 --> CodeIgniter\Filters\Exceptions\FilterException: El filtro no_sesion debe tener un alias coincidente definido.
[Method: GET, Route: login]
in SYSTEMPATH\Filters\Filters.php on line 590.
 1 SYSTEMPATH\Filters\Filters.php(590): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('no_sesion')
 2 SYSTEMPATH\Filters\Filters.php(641): CodeIgniter\Filters\Filters->enableFilter('no_sesion', 'before')
 3 SYSTEMPATH\CodeIgniter.php(467): CodeIgniter\Filters\Filters->enableFilters([...], 'before')
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
